# Generated by Django 3.1.3 on 2020-12-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20201216_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.BooleanField(default=False, null=True, verbose_name='Está ativo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('email', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('product', models.ManyToManyField(to='contents.Product', verbose_name='produtos')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
