version: "3"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "3500:3500"
